const $=s=>document.querySelector(s);
let config=defaultConfig(),program=[],sim=new RoverEngine(config,program),drag=null,lastPc=-1,lastRun=false,lastMessage='',accumulator=0;
const defaults={senseLoop:{type:'senseLoop',target:'pickup',leftRule:true,rightRule:true,pulse:.1,power:100},driveTime:{type:'driveTime',seconds:1,power:100},halt:{type:'halt'},grab:{type:'grab'},drop:{type:'drop'},wait:{type:'wait',seconds:1},wheelTime:{type:'wheelTime',left:100,right:0,seconds:.1},servoTime:{type:'servoTime',angle:29.5388,power:100,seconds:1},relayRoute:{type:'relayRoute',target:'pickup',straight:1,angle:29.5388,turnTime:1,power:100},relayGrab:{type:'relayGrab',target:'pickup',seconds:1,power:100},stop:{type:'stop'}};
for(const id of ['ultra','color','encoder','gyro','touch'])defaults[id+'Until']={type:id+'Until',compare:0,threshold:1,left:100,right:100};
Object.assign(defaults.senseLoop,{leftRule:false,rightRule:false,leftBlack:true,rightBlack:true,leftThenLeft:0,leftThenRight:100,rightThenLeft:100,rightThenRight:0});
function freshBlock(type){const b={...defaults[type]};for(const k of Object.keys(b))if((typeof b[k]==='number'&&k!=='power')||['leftBlack','rightBlack','target'].includes(k))b[k]=null;return b}
const names={senseLoop:'光電判斷循環',driveTime:'兩輪前進',halt:'兩輪停止',grab:'機械臂抓取',drop:'機械臂放下',wait:'等待',wheelTime:'獨立輪速',servoTime:'舵機轉向',relayRoute:'繼電器轉向序列',relayGrab:'繼電器定時抓放',stop:'結束程式'};
Object.assign(names,{ultraUntil:'超音波條件行駛',colorUntil:'顏色條件行駛',encoderUntil:'輪速條件行駛',gyroUntil:'朝向條件行駛',touchUntil:'碰撞條件行駛'});
function selectField(i,key,value,options){return '<select data-i="'+i+'" data-key="'+key+'"><option value="" disabled '+(value===null?'selected':'')+'>請選擇</option>'+options.map(([v,t])=>'<option value="'+v+'" '+(value===v?'selected':'')+'>'+t+'</option>').join('')+'</select>'}
const cls=t=>['grab','drop','relayGrab'].includes(t)?'action':['driveTime','wheelTime','servoTime','halt'].includes(t)?'motion':'flow';
function feedback(text,error=false){$('#purchase').textContent=text;$('#purchase').classList.toggle('error',error)}
function setConfiguration(next){const cost=configCost(next);if(next.parts.has('servo')&&next.motor===4){feedback('轉向舵機支援單馬達或雙馬達底盤。',true);hardware();return false}config=next;reset();hardware();feedback('配置已更新，總花費 '+cost+' 枚金幣。挑戰用更少的零件完成任務！');return true}
function hardware(){const cost=configCost(config);$('#remaining').textContent=cost;$('#spent').textContent=cost;$('#drivebadge').textContent=!config.motor?'未安裝馬達':config.parts.has('servo')?'舵機轉向':config.motor===1?'只可直行':'差速轉向';$('#spec').value=config.spec;$('#spec').disabled=sim.running;$('#motors').innerHTML=[[1,'單馬達','兩輪連動；需舵機才能轉向'],[2,'雙馬達','左右輪獨立控制'],[4,'四馬達','四輪分組差速']].map(([n,t,d])=>`<label class="motor"><input type="radio" name="motor" value="${n}" ${config.motor===n?'checked':''} ${sim.running?'disabled':''}><span><b>${t} <em>${MOTOR_COST[n]} 金幣</em></b><small>${d}</small></span></label>`).join('');$('#sensorcount').textContent=config.parts.size+' 個已裝';$('#sensors').innerHTML=PARTS.map(p=>`<label class="sensor"><input type="checkbox" data-part="${p.id}" ${config.parts.has(p.id)?'checked':''} ${sim.running?'disabled':''}><span><b>${p.name} <em>${p.price} 金幣</em></b><small>${p.desc}</small></span></label>`).join('');renderPalette()}
$('#motors').onchange=e=>{if(e.target.name==='motor')setConfiguration({...config,motor:+e.target.value,parts:new Set(config.parts)})};$('#sensors').onchange=e=>{const id=e.target.dataset.part;if(!id)return;const parts=new Set(config.parts);e.target.checked?parts.add(id):parts.delete(id);setConfiguration({...config,parts})};$('#spec').onchange=e=>setConfiguration({...config,spec:e.target.value,parts:new Set(config.parts)});
function num(i,key,value,min,max,step=.1){return `<input data-i="${i}" data-key="${key}" aria-label="第${i+1}步 ${key}" type="number" min="${min}" max="${max}" step="${step}" placeholder="自行填寫" value="${value??''}">`}
function station(i,b){return `<select data-i="${i}" data-key="target" aria-label="第${i+1}步 目標站"><option value="" disabled ${b.target===null?'selected':''}>請選擇</option><option value="pickup" ${b.target==='pickup'?'selected':''}>取物站</option><option value="finish" ${b.target==='finish'?'selected':''}>終點</option></select>`}
function direction(i,angle){return `<select data-i="${i}" data-key="angle" aria-label="第${i+1}步 轉向"><option value="" disabled ${angle===null?'selected':''}>請選擇</option><option value="-29.5388" ${angle<0?'selected':''}>左轉</option><option value="29.5388" ${angle>0?'selected':''}>右轉</option><option value="0" ${angle===0?'selected':''}>直行</option></select>`}
function wheel(i,key,value){return `<select data-i="${i}" data-key="${key}" aria-label="第${i+1}步 ${key==='left'?'左輪':'右輪'}"><option value="" disabled ${value===null?'selected':''}>請選擇</option><option value="100" ${value>0?'selected':''}>前進</option><option value="0" ${value===0?'selected':''}>停止</option></select>`}
function renderProgram(){lastPc=sim.pc;lastRun=sim.running;$('#program').innerHTML='<div class="start">⚑ 當按下執行</div>'+(!program.length?'<div class="emptyprogram">將積木加入這裡<br><small>選好硬體，再編寫控制邏輯。</small></div>':'')+program.map((b,i)=>{let inner='';if(b.type==='senseLoop')inner=`<div class="blockline">重複，直到攝像頭辨識 ${station(i,b)}</div><div class="nested"><label><input type="checkbox" data-i="${i}" data-key="rightRule" ${b.rightRule?'checked':''}> 如果右光電 = ${selectField(i,'rightBlack',b.rightBlack,[[true,'黑色'],[false,'白色']])}</label><div>→ 左輪 ${num(i,'rightThenLeft',b.rightThenLeft,0,100,1)} % · 右輪 ${num(i,'rightThenRight',b.rightThenRight,0,100,1)} %</div><label><input type="checkbox" data-i="${i}" data-key="leftRule" ${b.leftRule?'checked':''}> 如果左光電 = ${selectField(i,'leftBlack',b.leftBlack,[[true,'黑色'],[false,'白色']])}</label><div>→ 左輪 ${num(i,'leftThenLeft',b.leftThenLeft,0,100,1)} % · 右輪 ${num(i,'leftThenRight',b.leftThenRight,0,100,1)} %</div><div>暫停 ${num(i,'pulse',b.pulse,.02,2,.01)} 秒，再繼續</div><div>未觸發 → 兩輪直行</div></div>`;
else if(b.type==='driveTime')inner=`<div class="blockline">${num(i,'seconds',b.seconds,.05,30,.05)} 秒</div>`;
else if(b.type==='wheelTime')inner=`<div class="blockline">左輪 ${wheel(i,'left',b.left)}　右輪 ${wheel(i,'right',b.right)}</div><div class="blockline">持續 ${num(i,'seconds',b.seconds,.02,30,.01)} 秒</div>`;
else if(b.type==='servoTime')inner=`<div class="blockline">${direction(i,b.angle)} · ${num(i,'seconds',b.seconds,.05,30,.05)} 秒</div>`;
else if(b.type==='relayRoute')inner=`<div class="blockline">直行 ${num(i,'straight',b.straight,0,30,.001)} 秒</div><div class="blockline">${direction(i,b.angle)} ${num(i,'turnTime',b.turnTime,.01,15,.001)} 秒</div><div class="blockline">回正，直行直到辨識 ${station(i,b)}</div>`;
else if(b.type==='relayGrab')inner=`<div class="blockline">前進 ${num(i,'seconds',b.seconds,.05,30,.05)} 秒 → 停車</div><div class="blockline">在 ${station(i,b)} 自動抓取 / 放下</div>`;
else if(b.type==='wait')inner=`<div class="blockline">${num(i,'seconds',b.seconds,.05,30,.05)} 秒（保留輪速）</div>`;
if(b.type.endsWith('Until')){const id=b.type.slice(0,-5);inner='<div class="blockline">左輪 '+num(i,'left',b.left,0,100,1)+' % · 右輪 '+num(i,'right',b.right,0,100,1)+' %</div><div class="blockline">直到 '+selectField(i,'compare',b.compare,[[0,'≤'],[1,'='],[2,'≥']])+' '+(['color','touch'].includes(id)?selectField(i,'threshold',b.threshold,id==='color'?[[0,'無標記'],[1,'黃'],[2,'藍']]:[[0,'無'],[1,'觸發']]):num(i,'threshold',b.threshold,0,id==='gyro'?359:500,1))+' '+({ultra:'cm',gyro:'°',encoder:'cm/s',color:'',touch:''}[id])+' → 停止</div>';}
const error=blockRequirement(b,config)||parameterError(b);return `<div class="block ${cls(b.type)} ${sim.running&&i===sim.pc?'active':''} ${error?'invalid':''}" draggable="${!sim.running}" data-index="${i}"><div class="blocktitle"><b>${String(i+1).padStart(2,'0')}　${names[b.type]}</b><span></span><button data-up="${i}" aria-label="第${i+1}步上移">↑</button><button data-down="${i}" aria-label="第${i+1}步下移">↓</button><button data-delete="${i}" aria-label="第${i+1}步刪除">×</button></div>${inner}${error?'<div class="blockerror">'+error+'</div>':''}</div>`}).join('');$('#program').querySelectorAll('input,select,button').forEach(e=>e.disabled=sim.running);$('#clear').disabled=sim.running;$('#example').disabled=sim.running;$('#importProgram').disabled=sim.running;renderPalette()}
function renderPalette(){$('#palette').innerHTML=Object.entries(defaults).map(([t,b])=>{const error=blockRequirement(b,config);return `<button class="palettebtn ${cls(t)}" data-type="${t}" draggable="${!error&&!sim.running}" ${error||sim.running?'disabled':''}>${error?'▱':'＋'} ${names[t]}${error?'<small>'+error+'</small>':''}</button>`}).join('')}
$('#palette').onclick=e=>{const b=e.target.closest('[data-type]');if(b&&!b.disabled){program.push(freshBlock(b.dataset.type));renderProgram()}};
$('#program').onclick=e=>{if(sim.running)return;for(const [k,d]of [['up',-1],['down',1],['delete',0]])if(e.target.dataset[k]!==undefined){const i=+e.target.dataset[k];if(k==='delete')program.splice(i,1);else if(program[i+d])[program[i],program[i+d]]=[program[i+d],program[i]];reset()}};
$('#program').onchange=e=>{if(sim.running)return;const i=+e.target.dataset.i,k=e.target.dataset.key;if(!k)return;let v=e.target.value===''?null:e.target.type==='checkbox'?e.target.checked:['leftBlack','rightBlack'].includes(k)?e.target.value==='true':k==='target'?e.target.value:e.target.tagName==='SELECT'?Number(e.target.value):['angle','left','right'].includes(k)?Number(e.target.value):Math.max(+e.target.min,Math.min(+e.target.max,Number(e.target.value)||0));program[i][k]=v;sim.reset();renderProgram()};
document.addEventListener('dragstart',e=>{if(sim.running){e.preventDefault();return}const b=e.target.closest('[data-index],[data-type]');if(!b||b.disabled)return;drag=b.dataset.type?{type:b.dataset.type}:{index:+b.dataset.index};e.dataTransfer.setData('text/plain','rover-block')});$('#program').ondragover=e=>e.preventDefault();$('#program').ondrop=e=>{e.preventDefault();if(!drag||sim.running)return;const dest=e.target.closest('[data-index]');let i=dest?+dest.dataset.index:program.length;if(drag.type)program.splice(i,0,freshBlock(drag.type));else{const b=program.splice(drag.index,1)[0];if(i>drag.index)i--;program.splice(i,0,b)}drag=null;reset()};
function reset(){sim=new RoverEngine(config,program);accumulator=0;renderProgram();hardware();readings()}
$('#run').onclick=()=>{sim=new RoverEngine(config,program);sim.start();accumulator=0;renderProgram();hardware();readings()};$('#pause').onclick=()=>{sim.paused=!sim.paused;readings()};$('#reset').onclick=reset;$('#clear').onclick=()=>{program=[];reset()};$('#example').onclick=()=>{program=[freshBlock('driveTime'),{type:'halt'}];reset()};$('#guide').onclick=()=>$('#help').showModal();$('#closehelp').onclick=()=>$('#help').close();$('#zoom').onclick=()=>$('#structureModal').showModal();$('#closeStructure').onclick=()=>$('#structureModal').close();
function validateImport(data){if(!data||typeof data!=='object'||!data.config||!Array.isArray(data.program)||data.program.length>60)throw Error('無效的方案檔案');const c=data.config;if(![1,2,4].includes(c.motor)||!Object.hasOwn(SPEC_COST,c.spec)||!Array.isArray(c.parts)||c.parts.some(id=>!PARTS.some(p=>p.id===id)))throw Error('硬體配置無效');const next={motor:c.motor,spec:c.spec,parts:new Set(c.parts)};if(next.motor===4&&next.parts.has('servo'))throw Error('舵機不支援四馬達底盤');const clean=data.program.map(b=>{if(!b||!Object.hasOwn(defaults,b.type))throw Error('未知積木');const result={...defaults[b.type]};for(const k of Object.keys(result)){if(k==='type')continue;if(typeof result[k]==='number'){const v=Number(b[k]??defaults[b.type][k]);const ranges={compare:[0,2],threshold:[0,500],leftThenLeft:[0,100],leftThenRight:[0,100],rightThenLeft:[0,100],rightThenRight:[0,100],seconds:[.02,30],straight:[0,30],turnTime:[.01,15],angle:[-45,45],pulse:[.02,2],power:[10,100],left:[0,100],right:[0,100]};const [lo,hi]=ranges[k];if(!Number.isFinite(v)||v<lo||v>hi)throw Error('積木數值超出範圍');result[k]=v}else if(k==='target'){if(!['pickup','finish'].includes(b[k]))throw Error('無效站點');result[k]=b[k]}else{if(b[k]!==undefined&&typeof b[k]!=='boolean')throw Error('判斷設定無效');result[k]=b[k]??result[k]}}const err=blockRequirement(result,next);if(err)throw Error(err);return result});return {config:next,program:clean}}
$('#importProgram').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error('檔案太大');const data=validateImport(JSON.parse(await file.text()));config=data.config;program=data.program;reset();feedback('已載入方案；花費 '+configCost(config)+' 金幣。')}catch(err){feedback('未載入：'+err.message,true)}e.target.value=''};
function rect(g,x,y,w,h,color){g.fillStyle=color;g.fillRect(x,y,w,h)}
function box(g,x,y){rect(g,x-10,y-10,20,20,'#9d753b');rect(g,x-8,y-8,16,16,'#efc975');rect(g,x-2,y-8,4,16,'#fff2bc')}
function mapDraw(){const canvas=$('#map'),g=canvas.getContext('2d');g.clearRect(0,0,800,560);rect(g,0,0,800,560,'#eaf0df');g.strokeStyle='#dbe4d0';g.lineWidth=1;for(let x=0;x<800;x+=25){g.beginPath();g.moveTo(x,0);g.lineTo(x,560);g.stroke()}for(let y=0;y<560;y+=25){g.beginPath();g.moveTo(0,y);g.lineTo(800,y);g.stroke()}g.strokeStyle='#afbea0';g.setLineDash([6,6]);g.strokeRect(30,30,740,500);g.setLineDash([]);g.strokeStyle='#29382f';g.lineWidth=14;g.lineJoin='round';g.beginPath();TRACK.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.stroke();for(const [x,y,color,label]of [[110,450,'#9bbe80','起點'],[420,110,'#e9c77b','取物站'],[690,450,'#9ebed1','終點']]){rect(g,x-30,y-27,60,54,color);g.fillStyle='#496341';g.font='bold 17px Microsoft JhengHei';g.textAlign='center';g.fillText(label,x,y+50)}g.strokeStyle='#29382f';g.lineWidth=14;for(const s of [STATIONS.pickup,STATIONS.finish]){g.beginPath();if(s===STATIONS.pickup){g.moveTo(s.x-30,s.y);g.lineTo(s.x+30,s.y)}else{g.moveTo(s.x,s.y-27);g.lineTo(s.x,s.y+27)}g.stroke()}if(!sim.holding&&!sim.delivered)box(g,420,110);if(sim.delivered)box(g,690,450);g.fillStyle='#a0b28f';g.font='bold 17px monospace';g.fillText('SENSE → THINK → ACT',400,280);g.font='14px Microsoft JhengHei';g.fillText('觀察車輪、光電與攝像頭',400,306);
g.strokeStyle='#76a56b77';g.lineWidth=3;g.beginPath();sim.trail.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke();if(config.parts.has('camera')){g.fillStyle='#70a6be22';g.beginPath();const p=sim.point(20);g.moveTo(p.x,p.y);for(const side of [-30,30]){const q=sim.point(120,side);g.lineTo(q.x,q.y)}g.closePath();g.fill()}
g.save();g.translate(sim.x,sim.y);g.rotate(sim.a+Math.PI/2);rect(g,-14,-21,28,43,'#b9d597');for(const s of [-1,1]){g.save();g.translate(s*19,-11);if(config.parts.has('servo'))g.rotate(sim.steer*Math.PI/180);rect(g,-4,-8,8,17,'#344537');g.restore();rect(g,s*19-4,9,8,15,'#344537')}rect(g,-9,-7,18,19,'#57744e');for(const [side,n]of [['left',-1],['right',1]])if(config.parts.has(side))rect(g,n*10-3,-21,6,6,sim.sensor(side)?'#26392c':'#f2d978');if(config.parts.has('camera')){rect(g,-6,-25,12,7,'#6997b0');rect(g,-2,-26,4,4,'#192b34')}if(config.parts.has('arm')){g.strokeStyle=sim.armState==='落空'?'#c27657':'#ab8c4c';g.lineWidth=3;const reach=sim.armState==='伸出'||sim.armState==='落空'?28:24;g.beginPath();g.moveTo(-9,-14);g.lineTo(-9,-reach);g.lineTo(-4,-reach);g.moveTo(9,-14);g.lineTo(9,-reach);g.lineTo(4,-reach);g.stroke()}if(sim.holding)box(g,0,-28);g.restore();if(sim.armState==='落空'){const p=sim.point(28),s=STATIONS[sim.detectionTarget||'pickup'];g.strokeStyle='#c77d59';g.setLineDash([4,4]);g.beginPath();g.moveTo(p.x,p.y);g.lineTo(s.x,s.y);g.stroke();g.setLineDash([])}}
function structureDraw(canvas){const g=canvas.getContext('2d');g.save();g.scale(canvas.width/600,canvas.height/460);rect(g,0,0,600,460,'#203b32');g.strokeStyle='#355345';g.lineWidth=1;for(let x=0;x<600;x+=25){g.beginPath();g.moveTo(x,0);g.lineTo(x,460);g.stroke()}for(let y=0;y<460;y+=25){g.beginPath();g.moveTo(0,y);g.lineTo(600,y);g.stroke()}const has=id=>config.parts.has(id),color=id=>has(id)?'#b4d685':'#50685a';g.textAlign='center';g.fillStyle='#c3d6b5';g.font='16px monospace';g.fillText('↑ FRONT',300,31);rect(g,228,138,144,222,'#8cac76');rect(g,242,152,116,187,'#c1d7a0');rect(g,205,180,25,74,sim.left>0?'#82c777':'#53675b');rect(g,370,180,25,74,sim.right>0?'#82c777':'#53675b');rect(g,205,283,25,60,'#344e40');rect(g,370,283,25,60,'#344e40');if(config.motor){rect(g,262,238,76,60,'#426348');rect(g,278,250,44,35,'#7faa65');}for(const [id,x]of [['left',232],['right',350]]){rect(g,x,142,18,20,color(id));if(has(id))rect(g,x+4,147,10,9,sim.sensor(id)?'#111e18':'#fff4ba')}
rect(g,281,102,38,24,color('camera'));rect(g,290,96,20,13,has('camera')?'#78b6d0':'#50685a');rect(g,296,98,8,8,'#18342c');if(has('camera')){g.fillStyle='#72b5d029';g.beginPath();g.moveTo(300,94);g.lineTo(257,47);g.lineTo(343,47);g.closePath();g.fill()}
g.strokeStyle=color('arm');g.lineWidth=8;g.beginPath();g.moveTo(266,209);g.lineTo(267,129);g.lineTo(277,129);g.moveTo(334,209);g.lineTo(333,129);g.lineTo(323,129);g.stroke();if(sim.holding)box(g,300,130);rect(g,260,178,80,28,color('servo'));g.fillStyle='#213c32';g.font='bold 16px monospace';g.fillText(has('servo')?(sim.steer>0?'右轉':sim.steer<0?'左轉':'直行'):'未安裝',300,198);rect(g,258,309,84,28,color('relay'));g.fillStyle='#213c32';g.fillText(has('relay')?'TIMER':'—',300,328);
function label(text,x,y,tx,ty,id){g.strokeStyle=has(id)?'#a7c58c':'#65816c';g.lineWidth=1.5;g.beginPath();g.moveTo(tx,ty);g.lineTo(x<300?190:410,y-6);g.lineTo(x,y-6);g.stroke();g.textAlign=x<300?'left':'right';g.fillStyle=has(id)?'#d5e9c2':'#7e9681';g.font='17px Microsoft JhengHei';g.fillText(text,x,y-14)}label('前置攝像頭',565,85,315,105,'camera');label('左光電',26,160,240,150,'left');label('右光電',575,160,360,150,'right');label('機械臂',26,106,270,128,'arm');label('轉向舵機',575,213,340,190,'servo');label('時間繼電器',26,333,260,323,'relay');g.textAlign='left';g.fillStyle='#cbe4b5';g.font='17px Microsoft JhengHei';g.fillText('左輪 '+(sim.left>0?'前進':'停止'),26,255);g.textAlign='right';g.fillText('右輪 '+(sim.right>0?'前進':'停止'),575,273);g.textAlign='center';g.font='15px Microsoft JhengHei';g.fillStyle='#a5bd9a';g.fillText(!config.motor?'未安裝馬達':config.parts.has('servo')?'已安裝舵機':config.motor===1?'單馬達 · 兩輪連動':'已安裝獨立馬達',300,410);g.fillText('夾爪：'+sim.armState,300,438);g.restore()}
function cameraDraw(){const g=$('#cameraFeed').getContext('2d');rect(g,0,0,280,150,'#243c34');if(!config.parts.has('camera')){g.fillStyle='#9aaa95';g.font='16px Microsoft JhengHei';g.textAlign='center';g.fillText('尚未安裝攝像頭',140,78);return}g.strokeStyle='#58745a';for(let y=35;y<150;y+=25){g.beginPath();g.moveTo(0,y);g.lineTo(280,y);g.stroke()}g.fillStyle='#172a23';g.beginPath();g.moveTo(135,35);g.lineTo(145,35);g.lineTo(168,150);g.lineTo(112,150);g.fill();let target=sim.camera('pickup')&&!sim.holding&&!sim.delivered?'pickup':sim.camera('finish')?'finish':null;if(target){rect(g,105,45,70,60,target==='pickup'?'#e4c36e':'#88b6ce');g.strokeStyle='#b0ed8e';g.lineWidth=2;g.strokeRect(95,35,90,80);g.fillStyle='#dcf6c7';g.font='14px Microsoft JhengHei';g.textAlign='center';g.fillText(STATIONS[target].name,140,25)}else{g.fillStyle='#9fb692';g.font='13px Microsoft JhengHei';g.textAlign='center';g.fillText('搜尋站點標誌…',140,23)}}
function readings(){$('#run').disabled=sim.running;$('#pause').disabled=!sim.running;$('#pause').textContent=sim.paused?'▶ 繼續':'Ⅱ 暫停';$('#status').textContent=sim.paused?'已暫停':sim.status;for(const side of ['left','right'])$('#'+side+'Read').textContent=sim.sensor(side)===null?'未裝':sim.sensor(side)?'黑色':'白色';$('#wheelRead').textContent=sim.left===0&&sim.right===0?'停止':sim.left===0?'左輪暫停':sim.right===0?'右輪暫停':'前進';$('#cargo').textContent=sim.delivered?'已送達':sim.holding?'持有貨物':'未取物';$('#ruleLive').textContent=sim.running?sim.rule:'等待執行感測規則';const target=sim.detectionTarget||'pickup';$('#cameraState').textContent=!config.parts.has('camera')?'未安裝':sim.camera('pickup')&&!sim.holding?'辨識：取物站':sim.camera('finish')?'辨識：終點':'搜尋站點';$('#clockRead').textContent=sim.eventTime===null?'—':((sim.stopTime??sim.time)-sim.eventTime).toFixed(2)+' s';$('#gapRead').textContent=sim.eventTime===null?'—':(sim.clawError(target)/2).toFixed(1)+' cm';if(lastMessage!==sim.message){$('#log').textContent=sim.message;lastMessage=sim.message;$('#events').innerHTML=sim.trace.map(e=>`<li><time>${e.time.toFixed(2)} s</time> ${e.text}</li>`).join('')}const extras=[];if(config.parts.has('gyro'))extras.push('朝向 '+Math.round((sim.a*180/Math.PI+90+3600)%360)+'°');if(config.parts.has('encoder'))extras.push('輪速 L/R '+(sim.left/2).toFixed(1)+' / '+(sim.right/2).toFixed(1)+' cm/s');if(config.parts.has('touch'))extras.push('碰撞 '+(sim.x<=20||sim.x>=780||sim.y<=20||sim.y>=540?'觸發':'無'));if(config.parts.has('color'))extras.push('顏色 '+(Math.hypot(sim.x-420,sim.y-110)<32?'黃':Math.hypot(sim.x-690,sim.y-450)<32?'藍':'無標記'));if(config.parts.has('ultra')){let d=0;while(d<1000){const p=sim.point(d);if(p.x<20||p.x>780||p.y<20||p.y>540)break;d+=2}extras.push('前方边界 '+d/2+' cm')}$('#extraRead').textContent=extras.join(' · ')}
let last=performance.now();function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(sim.running&&!sim.paused){accumulator+=dt*Number($('#speed').value);while(accumulator>=1/120){sim.tick(1/120);accumulator-=1/120}}if(lastPc!==sim.pc||lastRun!==sim.running){renderProgram();hardware()}mapDraw();structureDraw($('#structure'));if($('#structureModal').open)structureDraw($('#structureLarge'));cameraDraw();readings();requestAnimationFrame(frame)}reset();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_rover_state',description:'Read robot hardware, cost, program, wheels, steering, and mission result.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||Object.keys(input).length)throw Error('Expected empty object');return {config:{motor:config.motor,spec:config.spec,parts:[...config.parts]},cost:configCost(config),budget:null,program,running:sim.running,delivered:sim.delivered,status:sim.status,wheels:[sim.left,sim.right],steering:sim.steer,message:sim.message,trace:sim.trace}}})).catch(()=>{})}catch{}}
